### ISSUE TITLE
Request path contains unescaped characters

### ISSUE THREAD

**Issue by CONSULitAS** [krauskopf/node-red-contrib-car-bmw#3]
beim Starten stürzt node red mit folgendem Protokoll ab:

```
17 Jan 15:46:38 - [info] Flows gestartet
Token expired, requesting a new one
17 Jan 15:46:38 - [info] [car-bmw-list:BMW Fahrzeuge] Token init completed: 
Token: Zo5U1Y5UbOepZPtqN00p4JE0c5texsFb
TokenType: Bearer
17 Jan 15:46:38 - [info] [car-bmw-get:i3 Service Partner] Token init completed: 
Token: Zo5U1Y5UbOepZPtqN00p4JE0c5texsFb
TokenType: Bearer
17 Jan 15:46:38 - [info] [car-bmw-get:i3 Service Partner] Path: /api/vehicle/servicepartner/v1/WBY1Z41080VZ75329 
17 Jan 15:46:38 - [red] Uncaught Exception:
17 Jan 15:46:38 - TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:115:13)
    at Object.request (https.js:289:10)
    at Object.request (/usr/lib/node_modules/node-red/node_modules/agent-base/patch-core.js:25:22)
    at Object.exports.call (/opt/fhem/.node-red/node_modules/node-red-contrib-car-bmw/lib/bmwrequest.js:26:20)
    at onSuccess (/opt/fhem/.node-red/node_modules/node-red-contrib-car-bmw/car-bmw.js:180:24)
    at readTokenData (/opt/fhem/.node-red/node_modules/node-red-contrib-car-bmw/lib/tokenmanager.js:97:5)
    at /opt/fhem/.node-red/node_modules/node-red-contrib-car-bmw/lib/tokenmanager.js:111:7
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

Nach Neustart:
```
Failed to use existing token from file, error SyntaxError: Unexpected end of JSON input, will request a new one
Failed to use existing token from file, error SyntaxError: Unexpected end of JSON input, will request a new one
Failed to use existing token from file, error SyntaxError: Unexpected end of JSON input, will request a new one
17 Jan 15:50:45 - [warn] [car-bmw-list:BMW Fahrzeuge] Failed to read token:Error: unable to get local issuer certificate
17 Jan 15:50:45 - [warn] [car-bmw-get:i3 Services] Failed to read token:Error: unable to get local issuer certificate
17 Jan 15:50:45 - [warn] [car-bmw-get:i3 Service Partner] Failed to read token:Error: unable to get local issuer certificate
Failed to read file: Error: ENOENT: no such file or directory, open 'currenttoken.json'
Failed to read file: Error: ENOENT: no such file or directory, open 'currenttoken.json'
Failed to read file: Error: ENOENT: no such file or directory, open 'currenttoken.json'
Failed to read file: Error: ENOENT: no such file or directory, open 'currenttoken.json'
```
in Endlosschleife

Danke für den Support!

**Comment by krauskopf** [comment]
Das liegt vermtulich an einer falschen VIN. Evtl. ist ein Leerzeichen zu viel am Ende. Mit der Version 0.1.3 habe ich eine Fehlerreaktion mit Warnung eingebaut, so dass es zu keinem Absturz mehr kommen sollte.

**Comment by CONSULitAS** [comment]
Danke für die Rückmeldung. Leider hatte ich Probleme mit dem Raspi und musste komplett neu aufsetzen.

Das wars. Die neue Version hat brav gemeckert! 👍
